Algoritmo "Área do Trapézio"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 29/08/2023
Var

   baseMenor, BaseMaior, h, area: real

Inicio


   baseMenor <- 6
   BaseMaior <- 8
   h <- 5
   
   area <- (baseMenor + BaseMaior)/2 * h
   escreva("A área da figura é: ", area)

Fimalgoritmo